set_property PACKAGE_PIN W5 [get_ports clock]
set_property PACKAGE_PIN W4 [get_ports {Anodes[3]}]
set_property PACKAGE_PIN V4 [get_ports {Anodes[2]}]
set_property PACKAGE_PIN U4 [get_ports {Anodes[1]}]
set_property PACKAGE_PIN U2 [get_ports {Anodes[0]}]
set_property PACKAGE_PIN W7 [get_ports {Cathodes[6]}]
set_property PACKAGE_PIN W6 [get_ports {Cathodes[5]}]
set_property PACKAGE_PIN U8 [get_ports {Cathodes[4]}]
set_property PACKAGE_PIN V8 [get_ports {Cathodes[3]}]
set_property PACKAGE_PIN U5 [get_ports {Cathodes[2]}]
set_property PACKAGE_PIN V5 [get_ports {Cathodes[1]}]
set_property PACKAGE_PIN U7 [get_ports {Cathodes[0]}]
set_property PACKAGE_PIN W15 [get_ports {RegisterIndex[4]}]
set_property PACKAGE_PIN W17 [get_ports {RegisterIndex[3]}]
set_property PACKAGE_PIN W16 [get_ports {RegisterIndex[2]}]
set_property PACKAGE_PIN V17 [get_ports {RegisterIndex[0]}]
set_property PACKAGE_PIN V16 [get_ports {RegisterIndex[1]}]



set_property IOSTANDARD LVCMOS33 [get_ports {Anodes[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Anodes[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Anodes[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Anodes[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Cathodes[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Cathodes[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Cathodes[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Cathodes[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Cathodes[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Cathodes[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Cathodes[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RegisterIndex[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RegisterIndex[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RegisterIndex[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RegisterIndex[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RegisterIndex[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clock]
